### ISSUE TITLE
An internal error occurred during: "Parse Tree Builder".

### ISSUE THREAD

**Issue by ghost** [grosenberg/AntlrDT#1]
```
An internal error occurred during: "Parse Tree Builder".
java.lang.NullPointerException
```

I'm installed this plugin from marketplace.

> Create demo project
> Copypaste example grammar/demo

![](http://image.prntscr.com/image/f7781da00d5b4cea9471b64e974b514c.png)

> And this error show in Eclipse

**Comment by grosenberg** [comment]
The folders containing the 'g4' grammars and the generated java files must be on the Java classpath, i.e., a Java source folder. Otherwise AntlrDT has no reliable way of finding them.
