### ISSUE TITLE
Can't install via update site

### ISSUE THREAD

**Issue by HJK181** [grosenberg/AntlrDT#13]
The update site links to https://github.com/grosenberg/AntlrDT/blob/master/www.certiv.net/updates which leads to a 404.
It's the same when I try to install over the Eclipse Marketplace.

**Comment by grosenberg** [comment]
Use the update site https://www.certiv.net/updates/

**Comment by HJK181** [comment]
Thx, this worked. However, I'm now getting 
```
Parser Loading class for 'null.QueryParser'.
Lexer Loading class for 'null.QueryLexer'.
Parser: Parser classname is uninitialized; re-save the source grammar.
Lexer: Lexer classname is uninitialized; re-save the source grammar.
General ---------------------------------------
...
Parser Loading class for 'foo.bar.QueryParser'.
Lexer Loading class for 'foo.bar.QueryLexer'.
Parser: Parser: failed to load class 'foo.bar.QueryParser' (foo.bar.QueryParser)
	(at java.net.URLClassLoader#findClass @435)
Lexer: Lexer: failed to load class 'foo.bar.QueryLexer' (foo.bar.QueryLexer)
	(at java.net.URLClassLoader#findClass @435)
General ---------------------------------------
```

My project is using Java 14, I assume that the Plugin only supports up to Java 8 (requirements section of the docs)? I'm having Lexer and Parser in a single file, is this valid?

**Comment by grosenberg** [comment]
Any version 11+ will work.

Split parser/lexer required.

**Comment by HJK181** [comment]
@grosenberg I've splitted Lexer and Parser but still facing
```
Parser Loading class for 'foo.bar.QueryParser'.
Lexer Loading class for 'foo.bar.QueryLexer'.
Parser: Parser: failed to load class 'foo.bar.QueryParser' (foo.bar.QueryParser)
	(at java.net.URLClassLoader#findClass @435)
Lexer: Lexer: failed to load class 'foo.bar.QueryLexer' (foo.bar.QueryLexer)
	(at java.net.URLClassLoader#findClass @435)
General ---------------------------------------
```
Any idea what could be the reason?
![image](https://user-images.githubusercontent.com/11541497/131332172-b530bc51-194f-47dd-8141-67cd31bc13c2.png)

**Comment by grosenberg** [comment]
Cannot tell from the too limited information provided.  Likely, the project setup does not follow the recommendation.
