### ISSUE TITLE
Problem with AntlrDT (NullException error)

### ISSUE THREAD

**Issue by lsancheze** [grosenberg/AntlrDT#2]
I am new using the tool, I have eclipse 4.6.2 (Neon.2) and when I try to make a simple example I get the error that is seen in the image. Please HELP!!!!!!!!!!

![error-antlr](https://cloud.githubusercontent.com/assets/26847080/24584126/88a27fd4-1730-11e7-85f0-598a07791a77.png)

UPDATE: Following the documentation, place the header and create the .java successfully. Also, place in the build path the antlr-4.6-completed.jar library. But it still throws the NullException error.

![error-antlr1](https://cloud.githubusercontent.com/assets/26847080/24584195/78629e08-1733-11e7-96c2-a153c1088cc3.png)

UPDATE: Problem solved. It did not have one of the requirements: Eclipse Zest Visualization Toolkit. Read the documentation http://www.certiv.net/projects/antlrdt.html

**Comment by grosenberg** [comment]
Resolved by user installing all required dependencies.
