### ISSUE TITLE
Path view: javafx class not found

### ISSUE THREAD

**Issue by jjfraney** [grosenberg/AntlrDT#6]
I cannot find instructions in the install of either eclipse or antlrdt for proper setup of javafx.  Can you give instructions or provide a link?

Knowing little about eclipse plugins, I'd expect the plugin would pull in the javafx libraries when installed.  No?

AntlrDT	4.9.0.20190204-2049	net.certiv.antlrdt.feature.feature.group	Certiv Analytics

Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200

java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+9-Ubuntu-119.04)
OpenJDK 64-Bit Server VM (build 12.0.2+9-Ubuntu-119.04, mixed mode)

OS: Ubuntu 19.04

Screenshot attached.
![antlrdt-paths-view-javafx-classnotfound](https://user-images.githubusercontent.com/95555/62494818-56c75600-b7a2-11e9-96aa-4b71737fdba3.png)

**Comment by grosenberg** [comment]
AntlrDT does not use JavaFX.

Make sure the Zest SDK 1.7 plugin is installed (listed in the 'Modeling' category of the platform install dialog). FWIW, it should install automatically as a dependency of the AntlrDT plugin, but if not, just add it manually.
