### ISSUE TITLE
Token's View does not allow input

### ISSUE THREAD

**Issue by jjfraney** [grosenberg/AntlrDT#7]
The Grammar and Source input panels in the view do not allow my input.

Theses accept focus, but do not respond to any keyboard key.

AntlrDT	4.9.0.20190204-2049	net.certiv.antlrdt.feature.feature.group	Certiv Analytics

Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200

java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+9-Ubuntu-119.04)
OpenJDK 64-Bit Server VM (build 12.0.2+9-Ubuntu-119.04, mixed mode)

OS: Ubuntu 19.04

attaching screen shot, but its difficult to show the action of not accepting input.

![Tokens-view-input-not-accepted](https://user-images.githubusercontent.com/95555/62495215-3f3c9d00-b7a3-11e9-99e3-48b3df16f39b.png)

**Comment by grosenberg** [comment]
The grammar name auto-populates when the editor finds the grammar in a 'valid' project directory. 

To be valid, both the grammar and the generated lexer/parser/visitor files must be within non-default source package directory(s) under the project root. This is necessary for the editor internals to find, evaluate, and build the live class files used to generate a token stream for presentation in the Token View and tree for the Parse View.
