### ISSUE TITLE
Unable to read repository when install AntlrDT for eclipse

### ISSUE THREAD

**Issue by 760374564** [grosenberg/AntlrDT#8]
I got an error when i install AntlrDT for eclipse like this:
```
Unable to read repository at http://www.certiv.net/updates/content.xml.
Certificate for <www.certiv.net> doesn't match any of the subject alternative names: [certiv.net]
```
I want to know why it happened and how I use it normally, thank you!

**Comment by grosenberg** [comment]
Fixed SSL certificate. P2 repository access works now. Please try again.
